/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import controller.MemberController;
import controller.MemberController.ChatThread;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
/**
 *
 * @author Hoang Pham
 */
public class ChatView extends javax.swing.JFrame {

    /**
     * Creates new form ChatView
     */
    MemberController mc;
    ClientController cc;
    
    public ImageIcon icLike;
    public ImageIcon icSad;
    public ImageIcon icHeart;
    public ImageIcon icSmile;
    public ImageIcon icCry;
    int room_id;
    public String nickname;
    public String role;
    
    public ChatView() {
        initComponents();
    }
    
    public ChatView(String nickname, int room_id, ClientController cc, String role) {
        initComponents();
        initEmoji();
        msg_area.setContentType("text/html");
        
        this.setTitle(nickname);
        this.room_id = room_id;
        this.nickname = nickname;
        this.cc = cc; 
        this.role = role;
        
        idroom_area.setText(""+room_id);
        msg_text.requestFocus();
        
        mc = new MemberController(nickname, room_id, role);
        ChatThread chat = mc.new ChatThread(mc);
        chat.start();
    }
    
    public void initEmoji() {
        icLike = new ImageIcon(getClass().getClassLoader().getResource("image/like.png"));
        icSad = new ImageIcon(getClass().getClassLoader().getResource("image/sad.png"));
        icHeart = new ImageIcon(getClass().getClassLoader().getResource("image/heart_eye.png"));
        icSmile = new ImageIcon(getClass().getClassLoader().getResource("image/smile.png"));
        icCry = new ImageIcon(getClass().getClassLoader().getResource("image/crying.png"));
        btn_icon_like.setIcon(icLike);
        btn_icon_sad.setIcon(icSad);
        btn_icon_heart.setIcon(icHeart);
        btn_icon_smile.setIcon(icSmile);
        btn_icon_cry.setIcon(icCry);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msg_text = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idroom_area = new javax.swing.JLabel();
        btn_show_members = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextPane();
        btn_icon_like = new javax.swing.JButton();
        btn_icon_sad = new javax.swing.JButton();
        btn_icon_heart = new javax.swing.JButton();
        btn_icon_smile = new javax.swing.JButton();
        btn_icon_cry = new javax.swing.JButton();
        btn_start_camera = new javax.swing.JButton();
        btn_show_camera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_text.setColumns(20);
        msg_text.setRows(5);
        msg_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_textKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                msg_textKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(msg_text);

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Room ID:");

        idroom_area.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btn_show_members.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_show_members.setText("Show members");
        btn_show_members.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_membersActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(msg_area);

        btn_icon_like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_likeActionPerformed(evt);
            }
        });

        btn_icon_sad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_sadActionPerformed(evt);
            }
        });

        btn_icon_heart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_heartActionPerformed(evt);
            }
        });

        btn_icon_smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_smileActionPerformed(evt);
            }
        });

        btn_icon_cry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icon_cryActionPerformed(evt);
            }
        });

        btn_start_camera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_start_camera.setText("Start camera");
        btn_start_camera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start_cameraActionPerformed(evt);
            }
        });

        btn_show_camera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_show_camera.setText("Show camera");
        btn_show_camera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_cameraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_icon_like, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_icon_sad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_icon_heart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_icon_smile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_icon_cry, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idroom_area, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_show_members)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_start_camera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_show_camera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idroom_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(btn_start_camera)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_show_members)
                    .addComponent(btn_show_camera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_icon_cry, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_icon_smile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_icon_heart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_icon_sad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_icon_like, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        String msg_client = "";
        msg_client = msg_text.getText().trim();
        if (!msg_client.equals("")) {
            MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
            this.mc.send_client_msg(msg_client);
            msg_text.setText("");
        }
    }//GEN-LAST:event_btn_sendActionPerformed

    private void msg_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_textKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            msg_text.setText(msg_text.getText() + '\n');
        }
    }//GEN-LAST:event_msg_textKeyPressed

    private void msg_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_textKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) == 0)) {
            String msg_client = "";
            msg_client = msg_text.getText().trim();
            if (!msg_client.equals("")) {
                msg_client = msg_client.replaceAll("\n", "<br>");
                MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
                this.mc.send_client_msg(msg_client);
                msg_text.setText("");
            }
        }
    }//GEN-LAST:event_msg_textKeyReleased

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        CloseWindow cw = new CloseWindow();
        cw.start();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_show_membersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_membersActionPerformed
        // TODO add your handling code here:
        String msg_client = "Show members!";
        this.mc.send_client_msg(msg_client);
    }//GEN-LAST:event_btn_show_membersActionPerformed

    private void btn_icon_likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_likeActionPerformed
        // TODO add your handling code here:
        String msg_client = "<img src='" + icLike.toString() + "'></img>";
        MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
        this.mc.send_client_msg(icLike);
    }//GEN-LAST:event_btn_icon_likeActionPerformed

    private void btn_icon_sadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_sadActionPerformed
        // TODO add your handling code here:
        String msg_client = "<img src='" + icSad.toString() + "'></img>";
        MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
        this.mc.send_client_msg(icSad);
    }//GEN-LAST:event_btn_icon_sadActionPerformed

    private void btn_icon_heartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_heartActionPerformed
        // TODO add your handling code here:
        String msg_client = "<img src='" + icHeart.toString() + "'></img>";
        MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
        this.mc.send_client_msg(icHeart);
    }//GEN-LAST:event_btn_icon_heartActionPerformed

    private void btn_icon_smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_smileActionPerformed
        // TODO add your handling code here:
        String msg_client = "<img src='" + icSmile.toString() + "'></img>";
        MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
        this.mc.send_client_msg(icSmile);
    }//GEN-LAST:event_btn_icon_smileActionPerformed

    private void btn_icon_cryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icon_cryActionPerformed
        // TODO add your handling code here:
        String msg_client = "<img src='" + icCry.toString() + "'></img>";
        MemberController.setMsg_area("[You]:&nbsp&nbsp " + msg_client);
        this.mc.send_client_msg(icCry);
    }//GEN-LAST:event_btn_icon_cryActionPerformed

    private void btn_start_cameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start_cameraActionPerformed
        // TODO add your handling code here:
        String msg_client = "Start camera!";
        this.mc.send_client_msg(msg_client);
        
    }//GEN-LAST:event_btn_start_cameraActionPerformed

    private void btn_show_cameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_cameraActionPerformed
        // TODO add your handling code here:
        VideoRecieveView vrv = new VideoRecieveView(nickname, room_id);
        vrv.setVisible(true);
    }//GEN-LAST:event_btn_show_cameraActionPerformed
    
    public void close() {
        WindowEvent close_window = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close_window);
    }
    
    class CloseWindow extends Thread{
        @Override
        public void run() {
            MemberController.setMsg_area("[SERVER]:&nbsp&nbsp You are trying to exit. Window will be closed.");
            try {
                Thread.sleep(1000);
                mc.member_socket.close();
                cc.client_socket.close();
            }
            catch(Exception e) {
                System.out.println(e);
            }
            close();
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_icon_cry;
    private javax.swing.JButton btn_icon_heart;
    private javax.swing.JButton btn_icon_like;
    private javax.swing.JButton btn_icon_sad;
    private javax.swing.JButton btn_icon_smile;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_show_camera;
    private javax.swing.JButton btn_show_members;
    private javax.swing.JButton btn_start_camera;
    private javax.swing.JLabel idroom_area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextPane msg_area;
    private javax.swing.JTextArea msg_text;
    // End of variables declaration//GEN-END:variables
}
